### ISSUE TITLE
Pixel 0 not being rendered in 320x240 mode

### ISSUE THREAD

**Issue by ixmeins** [picocomputer/rp6502#21]
The left most pixel in each horizontal line is not being rendered in 320x240 graphics mode.
The issue is possibly a pre-increment of the memory pointer in line 390 or vga.c
I can not successfully build the vga uf2 so I am unable to test the fix. I can build the ria uf2.

**Comment by rumbledethumps** [comment]
pixel: commit 3531219
build: commit 44a13da
