### ISSUE TITLE
enhance ria/sys/com driver for better line input

### ISSUE THREAD

**Issue by rumbledethumps** [picocomputer/rp6502#42]
* chars are overtyping, they should be inserting.
 * support home and end keys

Add your requests and findings here.

**Comment by CHiPs44** [comment]
- support Ctrl + Left Arrow / Ctrl + Right Arrow to move from current "word" to previous / next one?

**Comment by rumbledethumps** [comment]
also...
* move by word added
* ctrl-a/e/f/b added
