### ISSUE TITLE
Dynamic keyboard layout

### ISSUE THREAD

**Issue by CHiPs44** [picocomputer/rp6502#46]
Instead of compile-time option to configure keyboard layout, it would be great to have it dynamically loaded, and have configuration support, too.

Another advantage is that RIA/VGA UF2 releases could be "agnostic" about this instead of using merican / english default.

And another idea would be to have these keyboard layouts as binary files on the SD card.

This is perhaps too long sighted for now.

**Comment by rumbledethumps** [comment]
Duplicate of #8.
