### ISSUE TITLE
How is other IO besides the VIA mapped?

### ISSUE THREAD

**Issue by cbmeeks** [picocomputer/rp6502#55]
I've been studying the schematic and, correct me if I'm wrong, it would seem the VIA would be turned on with the following addresses:

FF00 to FFE0.

It is only setting pins A15:A5 does the VIA turn off.  Meaning, if IORQ = ON and RREQ = OFF, then the VIA is enabled.

How would, for example, another VIA be selected with that memory map?

**VIA IS ON**

![image](https://github.com/picocomputer/rp6502/assets/49341/5227c145-6be1-4b4d-a2c6-bd229e88bdf4)

** VIA IS OFF**

![image](https://github.com/picocomputer/rp6502/assets/49341/9c90403a-928b-4492-83a9-2eb72dcbaa81)

Thanks

**Comment by rumbledethumps** [comment]
What "other VIAs" are you trying to select? There's only one in the reference design.

**Comment by cbmeeks** [comment]
I mean if I wanted to add another VIA or some other IC.

**Comment by rumbledethumps** [comment]
There's only one VIA in the reference design. This is working as intended. If you want to design something else then you have to do the engineering.

**Comment by cbmeeks** [comment]
I think you are getting too hung up on "the other via".  My point was if I wanted to add other IC's to the design in addition to the existing via.  It doesn't seem possible with this design.

But ok....lol
